name: mthesis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - blas=1.0=mkl
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py38h06a4308_0
  - cffi=1.14.5=py38h261ae71_0
  - freetype=2.10.4=h5ab3b9f_0
  - future=0.18.2=py38_1
  - jpeg=9d=h36c2ea0_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.15.6=h780b84a_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h27cfd23_0
  - llvm-openmp=11.1.0=h4bd325d_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py38hff7bd54_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=py38h06a4308_0
  - pycparser=2.20=py_2
  - python=3.8.3=hcff3b4d_2
  - python_abi=3.8=1_cp38
  - pytorch=1.8.0=cpu_py38he614459_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.15.0=py38h06a4308_0
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.35.2=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.9.0=py38h89b28b9_0_cpu
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
prefix: /home/ce/anaconda3/envs/mthesis
